name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request and release events
  pull_request:
  release:
    types: [published]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  pytest:
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python packages
        run: |
          pip install wheel
      - name: Build mycat
        run: |
          python setup.py bdist_wheel
      - name: Install mycat
        run: |
          pip install mycat[CI] --find-links dist
      - name: Python UnitTest
        run: |
          cd tests
          sh run.sh
